import React from "react";
import Users from "../post/Users";
import "./userspage.css";
import { List } from "@mui/material";
import Paper from "@mui/material/Paper";
import ListSubheader from "@mui/material/ListSubheader";

const UsersPage = () => {
  const messages = [
    {
      id: 1,
      username: "Blejn",
      secondary:
        "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person: "/static/images/avatar/5.jpg",
      status: true,
    },
    {
      id: 2,
      username: "Madzia",
      secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
      person: "/static/images/avatar/1.jpg",
      status: true,
    },
    {
      id: 3,
      username: "Mordunio",
      secondary:
        "I am try out this new BBQ recipe, I think this might be amazing",
      person: "/static/images/avatar/2.jpg",
      status: true,
    },
    {
      id: 4,
      username: "Essa",
      secondary: "I have the tickets to the ReactConf for this year.",
      person: "/static/images/avatar/3.jpg",
      status: false,
    },
    {
      id: 5,
      username: "Mordunio",
      secondary:
        "My appointment for the doctor was rescheduled for next Saturday.",
      person: "/static/images/avatar/4.jpg",
      status: false,
    },
    {
      id: 6,
      username: "Mordunio",
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
      person: "/static/images/avatar/5.jpg",
    },
    {
      id: 7,
      username: "Kuba",
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
      person: "/static/images/avatar/1.jpg",
      status: true,
    },
  ];
  return (
    <div className="postpage_container">
      <React.Fragment>
        <Paper square sx={{ pb: "50px" }}>
          <List sx={{ mb: 2 }}>
            <ListSubheader sx={{ bgcolor: "background.paper" }}>
              Active Users
            </ListSubheader>
            {messages.map(({ id, primary, username, person, status }) => (
              <Users
                id={id}
                primary={primary}
                username={username}
                person={person}
                status={status}
              />
            ))}
          </List>
        </Paper>
      </React.Fragment>
    </div>
  );
};

export default UsersPage;
